# Generated by Django 5.0.6 on 2024-06-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='media/')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itens.tipo')),
            ],
        ),
    ]
