# Generated by Django 5.0.6 on 2024-06-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_rename_item_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='contato',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
