# Generated by Django 5.0.6 on 2024-06-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_itens_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens',
            name='contato',
        ),
    ]
