# Generated by Django 5.0.6 on 2024-06-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0004_remove_itens_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='preco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
