# Generated by Django 5.0.6 on 2024-06-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0006_alter_itens_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itens',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
